language: node_js
node_js:
      - '6'
      - '8'
      - 'node'
addons:
      firefox: latest
cache:
      directories:
            - node_modules
before_script:
      - 'export DISPLAY=:99.0'
      - sh -e /etc/init.d/xvfb start
      - npm install -g gulp-cli
script:
      - npm run build
      - 'gulp format:enforce'
      - npm test
after_success: npm run coverage
