language: node_js

cache:
  directories:
    - "node_modules"

git:
  depth: 5

before_install:
  - npm i -g npm@latest

install:
  - npm ci
  - npm run build:dev

jobs:
  include:
    - state: "Test"
      name: "Unit Test Node v12"
      script: npm test
      node_js: 12
      after_success: npm run coverage

    - state: "Test"
      name: "Unit Test Node v10"
      script: npm test
      node_js: 10
    
    - state: "Test"
      name: "Unit Test Node v8"
      script: npm test
      node_js: 8

    - state: "Test"
      name: "Integration Test"
      install: skip
      before_install: skip
      before_script: skip
      addons: skip
      script:
        sudo service mysql stop &&
        bash ./scripts/prepare.sh &&
        npm run integration-test
      node_js: 12

    - stage: "Test"
      name: "Lint"
      script: npm run lint
      node_js: 12

    - stage: "Test"
      name: "Build samples"
      script: npm run build:samples
      node_js: 12

