version: 2
jobs:
  build:
    working_directory: ~/wd
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run build:dev
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Lint
          command: npm lint